
import CompositeDP.ComboItem;
import CompositeDP.ItemComponent;
import FactoryDP.Store;
import IteratorDP.Aggregate;
import IteratorDP.Iterator;
import ObserverDP.IObserver;
import SharedClasses.Customer;
import SharedClasses.Item;
import SharedClasses.Mall;
import SharedClasses.ShoppingCart;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
//import java.util.Iterator;
//import java.util.Iterator;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author fr-pa
 */
public class mallScreen extends javax.swing.JFrame {

    /**
     * Creates new form mallScreen
     */
    Mall bMall;
    Vector<ItemComponent> items;
    Vector<ItemComponent> comboitems;
    Vector<Store> stores;
    Vector<Customer> customers;
    Vector<Store> mallStores;

    GameStoreFactory gFactory;
    BookStoreFactory bFactory;
    ShoeStoreFactory shFactory;

    public mallScreen() {
        initComponents();
        items = new Vector<>();
        comboitems = new Vector();
        customers = new Vector<>();
        stores = new Vector<>();
        mallStores = new Vector<>();

        lodStoreCombo();

        lodCustomersCombo();
        lodStoreCustomersCombo();
        lodCustStoreCombo();
        lodStoreObsrvrCombo();
        cmbComboItems.setModel(populateCombo());
        cmbComboItems.setRenderer(new ComboBoxRenderer());
        CmbItemComp.setModel(populate());
        CmbItemComp.setRenderer(new ComboBoxRenderer());
        addIntiValues();
        cmbItemsForSale.setModel(populate());
        cmbItemsForSale.setRenderer(new ComboBoxRenderer());
        cmbCustStores.setModel(lodStoreCombo());
        cmbCustStores.setRenderer(new ComboBoxRenderer());
        cmbStoreCustomers.setModel(lodCustomersCombo());
        cmbStoreCustomers.setRenderer(new ComboBoxRenderer());
        cmbStoresObsrvr.setModel(lodStoreCombo());
        cmbStoresObsrvr.setRenderer(new ComboBoxRenderer());
        cmbCustomers.setModel(lodCustomersCombo());
        cmbCustomers.setRenderer(new ComboBoxRenderer());
        cmbStores.setModel(lodStoreCombo());
        cmbStores.setRenderer(new ComboBoxRenderer());
//        cmbShowStoreObsCmb.setModel(lodStoreCombo());
//        cmbShowStoreObsCmb.setRenderer(new ComboBoxRenderer());
        cmbMallStores.setModel(lodStoreCombo());
        cmbMallStores.setRenderer(new ComboBoxRenderer());
        cmbMallCustomers.setModel(lodCustomersCombo());
        cmbMallCustomers.setRenderer(new ComboBoxRenderer());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtStoreName = new javax.swing.JTextField();
        txtStoreId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rdbShoe = new javax.swing.JRadioButton();
        rdbBook = new javax.swing.JRadioButton();
        rdbGame = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        cmbItemsForSale = new javax.swing.JComboBox<>();
        cmbStores = new javax.swing.JComboBox<>();
        btnAddItem_store = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        btnAddCust_Store = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmbStoreCustomers = new javax.swing.JComboBox<>();
        cmbCustStores = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnShowStoreCustomers = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        cmbCustomers = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnAdd_Observer = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cmbStoresObsrvr = new javax.swing.JComboBox<>();
        btnRemoveObserver = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCompoItemID = new javax.swing.JTextField();
        txtComboItemName = new javax.swing.JTextField();
        btnCreatCompoItem = new javax.swing.JButton();
        cmCobositeCombo = new javax.swing.JPanel();
        CmbItemComp = new javax.swing.JComboBox<>();
        cmbComboItems = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PrintItem = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        txtItemPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtItemID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnNewItem = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cmbMallStores = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        cmbMallCustomers = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtcustomerID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setText("Clear Text");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Welcome To Mall"));

        jPanel1.setAutoscrolls(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add New Store"));

        jButton1.setText("Create Store");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Store ID");

        jLabel1.setText("Store Name");

        buttonGroup1.add(rdbShoe);
        rdbShoe.setText("Shoe");

        buttonGroup1.add(rdbBook);
        rdbBook.setText("Book");

        buttonGroup1.add(rdbGame);
        rdbGame.setSelected(true);
        rdbGame.setText("Game");

        jLabel19.setText("Choose Store Type");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(rdbGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(rdbBook)
                        .addGap(18, 18, 18)
                        .addComponent(rdbShoe))
                    .addComponent(txtStoreName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStoreId, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(73, 73, 73))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbGame)
                    .addComponent(rdbBook)
                    .addComponent(rdbShoe)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStoreId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Sale Items to Store"));

        cmbItemsForSale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbStores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStores.setSelectedItem(cmbComboItems);

        btnAddItem_store.setText("add item to store");
        btnAddItem_store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItem_storeActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose from Stoers List");

        jLabel5.setText("Chosse from Items List");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddItem_store, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(cmbItemsForSale, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStores, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbStores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbItemsForSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddItem_store)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Customers To Store"));

        btnAddCust_Store.setText("Add Customer ");
        btnAddCust_Store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCust_StoreActionPerformed(evt);
            }
        });

        jLabel13.setText("Choose Customer:");

        cmbStoreCustomers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCustStores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCustStores.setSelectedItem(cmbComboItems);

        jLabel14.setText("Stores List:");

        btnShowStoreCustomers.setText("Show Store Customers");
        btnShowStoreCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowStoreCustomersActionPerformed(evt);
            }
        });

        jButton7.setText("Remove Customer ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowStoreCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbStoreCustomers, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(btnAddCust_Store, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cmbCustStores, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCustStores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbStoreCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCust_Store)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowStoreCustomers))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Observers"));

        cmbCustomers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Choose Customer:");

        btnAdd_Observer.setText("Add Observer");
        btnAdd_Observer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_ObserverActionPerformed(evt);
            }
        });

        jLabel15.setText("Stores List:");

        cmbStoresObsrvr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStoresObsrvr.setSelectedItem(cmbComboItems);

        btnRemoveObserver.setText("Remove Observer");
        btnRemoveObserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveObserverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbStoresObsrvr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCustomers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btnAdd_Observer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoveObserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStoresObsrvr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(11, 11, 11)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd_Observer)
                    .addComponent(btnRemoveObserver))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Stores", jPanel1);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Add New Item"));

        jLabel10.setText("Item ID:");

        jLabel9.setText("Item Name:");

        txtCompoItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompoItemIDActionPerformed(evt);
            }
        });

        txtComboItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComboItemNameActionPerformed(evt);
            }
        });

        btnCreatCompoItem.setText("Create Item");
        btnCreatCompoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatCompoItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCompoItemID)
                    .addComponent(txtComboItemName)
                    .addComponent(btnCreatCompoItem, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompoItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComboItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreatCompoItem)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        cmCobositeCombo.setBorder(javax.swing.BorderFactory.createTitledBorder("Add items To ComboItem"));
        cmCobositeCombo.setToolTipText("");

        CmbItemComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbComboItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbComboItems.setSelectedItem(CmbItemComp);

        jButton3.setText("Add to Compo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Composite Item:");

        jLabel17.setText("Mixed Items:");

        PrintItem.setText("Print Items");
        PrintItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cmCobositeComboLayout = new javax.swing.GroupLayout(cmCobositeCombo);
        cmCobositeCombo.setLayout(cmCobositeComboLayout);
        cmCobositeComboLayout.setHorizontalGroup(
            cmCobositeComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmCobositeComboLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cmCobositeComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(cmCobositeComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CmbItemComp, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cmCobositeComboLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PrintItem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbComboItems, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        cmCobositeComboLayout.setVerticalGroup(
            cmCobositeComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmCobositeComboLayout.createSequentialGroup()
                .addGroup(cmCobositeComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbComboItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(cmCobositeComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbItemComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmCobositeComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(PrintItem))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmCobositeCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmCobositeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Composite Item", jPanel6);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Add New Item"));

        jLabel8.setText("Item Price");

        jLabel7.setText("Item Name");

        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });

        txtItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemIDActionPerformed(evt);
            }
        });

        jLabel6.setText("Item ID");

        btnNewItem.setText("Create Item");
        btnNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNewItem, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(txtItemID)
                    .addComponent(txtItemPrice, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewItem)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 150, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Item", jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(591, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Items", jPanel4);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Stores To Mall"));

        jLabel20.setText("Select Store");

        cmbMallStores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setText("Add Store To Mall");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbMallStores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMallStores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Customer To Mall"));

        jLabel21.setText("Select customer");

        cmbMallCustomers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setText("Add Customer to MaLL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setText("Remove Customer from MaLL");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbMallCustomers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cmbMallCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(737, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mange Malls", jPanel7);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Add New Customer"));

        jLabel11.setText("Customer ID");

        jLabel4.setText("Customer Name");

        jButton2.setText("Add Customer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtcustomerID)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(txtCustomerName))
                .addGap(153, 153, 153))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtcustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(706, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Customers", jPanel3);

        jScrollPane1.setViewportView(jTabbedPane1);

        jScrollPane3.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Store gStore;
        Store bStore;
        jTextArea1.append("\n");
        if (rdbBook.isSelected()) {
            if (!alertStore()) {

                bFactory = BookStoreFactory.getFactoryInstance();
                bStore = bFactory.createStore();
                bStore.setStoreID(txtStoreId.getText());
                bStore.setStoreName(txtStoreName.getText());
                stores.add(bStore);
                jTextArea1.append("A new Store has been added, Store ID: " + bStore.getStoreID() + " ,Store Name: " + bStore.getStoreName() + "\n");
               
                clear();
            }
        } else if (rdbGame.isSelected()) {
            if (!alertStore()) {
                gFactory = GameStoreFactory.getFactoryInstance();

                gStore = gFactory.createStore();
                gStore.setStoreID(txtStoreId.getText());
                gStore.setStoreName(txtStoreName.getText());
                String str = "A new Store has been added, Store ID: " + gStore.getStoreID() + " ,Store Name: " + gStore.getStoreName();
                jTextArea1.append(str + "\n");
                stores.add(gStore);
                clear();
            }
        } else if (rdbShoe.isSelected()) {
            if (!alertStore()) {
                /*Create A new Shoe Store*/
                shFactory = ShoeStoreFactory.getFactoryInstance();
                Store shStore = shFactory.createStore();

                shStore.setStoreID(txtStoreId.getText());
                shStore.setStoreName(txtStoreName.getText());
                stores.add(shStore);
                jTextArea1.append("A new Store has been added, Store ID: " + shStore.getStoreID() + " ,Store Name: " + shStore.getStoreName() + "\n");
                clear();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void txtComboItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComboItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComboItemNameActionPerformed

    private void btnCreatCompoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatCompoItemActionPerformed
        if (!alertComboItem()) {
            ItemComponent itm;
            itm = new ComboItem(txtComboItemName.getText(), txtCompoItemID.getText());
            items.add(itm);
            comboitems.add(itm);
            jTextArea1.append(itm.print().toString());        // TODO add your handling code here:
            clear();

    }//GEN-LAST:event_btnCreatCompoItemActionPerformed
    }
    private void txtItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtItemIDActionPerformed

    private void btnNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewItemActionPerformed
        // TODO add your handling code here:

        if (!alertItem()) {
            try {
                ItemComponent itm;

                Double num = Double.parseDouble(txtItemPrice.getText());
                itm = new Item(txtItemID.getText(), txtItemName.getText(), num);
                items.add(itm);
                jTextArea1.append(itm.print().toString());
            } catch (NumberFormatException e1) {
                JOptionPane.showMessageDialog(this, "Please Note,Numbers only allowed in the field Price!!!");
            }

        }
        clear();
    }//GEN-LAST:event_btnNewItemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (!alertCustomer()) {
                Customer c;
                c = new Customer(txtcustomerID.getText(), txtCustomerName.getText(), new ShoppingCart(), jTextArea1);
                customers.add(c);
                jTextArea1.append(c.getCustomerName() + " Customer Has been Created " + "\n");
                clear();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCompoItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompoItemIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompoItemIDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            ItemComponent comboMaster = (ItemComponent) cmbComboItems.getSelectedItem();
            ItemComponent combo = (ItemComponent) CmbItemComp.getSelectedItem();
            comboMaster.add(combo);
            items.add(combo);
            jTextArea1.append(comboMaster.print().toString());
        } catch (Exception e) {
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAdd_ObserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_ObserverActionPerformed
        // TODO add your handling code here:
        try {
            Store currentStore = (Store) cmbStoresObsrvr.getSelectedItem();
            Customer customer = (Customer) cmbCustomers.getSelectedItem();
            currentStore.registerObserver(customer);
            jTextArea1.append("New Observer added: " + customer.getCustomerName() + " To Store: " + currentStore.getStoreName() + "\n");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAdd_ObserverActionPerformed

    private void btnAddCust_StoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCust_StoreActionPerformed
        // TODO add your handling code here:
        try {
            Store currentStore = (Store) cmbCustStores.getSelectedItem();
            Customer item = (Customer) cmbStoreCustomers.getSelectedItem();
            currentStore.enter(item);
          jTextArea1.append(currentStore.getMsg());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnAddCust_StoreActionPerformed

    private void btnAddItem_storeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItem_storeActionPerformed
        // TODO add ysour handling code here:
        try {
            System.out.println("inside btnAddItem_storeActionPerformed\n");
            Store currentStore = (Store) cmbStores.getSelectedItem();
            ItemComponent item = (ItemComponent) cmbItemsForSale.getSelectedItem();
            jTextArea1.append("\n");
            currentStore.addItem(item);
            jTextArea1.append(currentStore.getMsg());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnAddItem_storeActionPerformed

    private void btnShowStoreCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowStoreCustomersActionPerformed
        // TODO add your handling code here:
        try {
            System.out.println(" inside btnShowStoreCustomersActionPerformed\n");
            Store currentStore = (Store) cmbStores.getSelectedItem();
            System.out.println(currentStore.getStoreName() + " \n");
            Iterator itr = currentStore.CreateIterator();
            int i=0;
             
            while (itr.hasNext()) {
             
            Customer c = (Customer) itr.next();
//           
                jTextArea1.append(currentStore.getStoreName() + " : Customers : " + c.getCustomerName() + "\n");
                       
            }
            
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnShowStoreCustomersActionPerformed

    private void PrintItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintItemActionPerformed
        // TODO add your handling code here:
        System.out.print(cmbComboItems.getSelectedIndex() );
         if (cmbComboItems.getSelectedIndex() == -1  )
          {
                 JOptionPane.showMessageDialog(this, "Please Select a Composite Item First");
          }
         else{
        ItemComponent itm = (ItemComponent) cmbComboItems.getSelectedItem();
        Iterator iterator = itm.CreateIterator();
         
      
        boolean i = iterator.hasNext();
        
        StringBuilder sb = new StringBuilder();
     
       sb.append(itm.print());
        while (iterator.hasNext()) {
         
           
            ItemComponent c = (ItemComponent) iterator.next();
            sb.append(c.print());
            jTextArea1.append(sb.toString());
        }

        }
    }//GEN-LAST:event_PrintItemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            Store currentStore = (Store) cmbMallStores.getSelectedItem();
            bMall.addStore(currentStore);
            jTextArea1.append(bMall.getMsg());

        } catch (Exception e) {

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
             Customer c= (Customer) cmbMallCustomers.getSelectedItem();
             bMall.enter(c);
             jTextArea1.append(bMall.getMsg());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnRemoveObserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveObserverActionPerformed
        // TODO add your handling code here:
        try
        {
            Store s =(Store)cmbStoresObsrvr.getSelectedItem();
            IObserver o =(IObserver)cmbCustomers.getSelectedItem();
            s.removeObserver(o);
            jTextArea1.append(s.getMsg());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_btnRemoveObserverActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try
        {
            Store s =(Store)cmbCustStores.getSelectedItem();
            Customer o =(Customer)cmbStoreCustomers.getSelectedItem();
            s.exit(o);
            jTextArea1.append(s.getMsg());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Customer cust =(Customer)cmbMallCustomers.getSelectedItem();
        bMall.exit(cust);
        jTextArea1.append("\n");
        jTextArea1.append(bMall.getMsg());
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mallScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mallScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mallScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mallScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mallScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbItemComp;
    private javax.swing.JButton PrintItem;
    private javax.swing.JButton btnAddCust_Store;
    private javax.swing.JButton btnAddItem_store;
    private javax.swing.JButton btnAdd_Observer;
    private javax.swing.JButton btnCreatCompoItem;
    private javax.swing.JButton btnNewItem;
    private javax.swing.JButton btnRemoveObserver;
    private javax.swing.JButton btnShowStoreCustomers;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel cmCobositeCombo;
    private javax.swing.JComboBox<String> cmbComboItems;
    private javax.swing.JComboBox<String> cmbCustStores;
    private javax.swing.JComboBox<String> cmbCustomers;
    private javax.swing.JComboBox<String> cmbItemsForSale;
    private javax.swing.JComboBox<String> cmbMallCustomers;
    private javax.swing.JComboBox<String> cmbMallStores;
    private javax.swing.JComboBox<String> cmbStoreCustomers;
    private javax.swing.JComboBox<String> cmbStores;
    private javax.swing.JComboBox<String> cmbStoresObsrvr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rdbBook;
    private javax.swing.JRadioButton rdbGame;
    private javax.swing.JRadioButton rdbShoe;
    private javax.swing.JTextField txtComboItemName;
    private javax.swing.JTextField txtCompoItemID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtStoreId;
    private javax.swing.JTextField txtStoreName;
    private javax.swing.JTextField txtcustomerID;
    // End of variables declaration//GEN-END:variables

    private boolean alertStore() {
        boolean flg = false;
        if (txtStoreId.getText().equals("") || txtStoreName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "please enter store name, id");
            flg = true;
        }
        return flg;
    }

    private boolean alertComboItem() {
        boolean flg = false;
        if (txtCompoItemID.getText().equals("") || txtComboItemName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "please enter CompoITem name, id");
            flg = true;
        }
        return flg;
    }

    private boolean alertItem() {
        boolean flg = false;
        if (txtItemID.getText().equals("") || txtItemID.getText().equals("") || txtItemPrice.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "please enter ITem name, id, Price");
            flg = true;
        }

        return flg;
    }

    private boolean alertCustomer() {
        boolean flg = false;
        if (txtcustomerID.getText().equals("") || txtCustomerName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "please enter Customer name, id");
            flg = true;
        }
        return flg;
    }

    private DefaultComboBoxModel lodStoreCombo() {
        DefaultComboBoxModel dcm;
        dcm = new DefaultComboBoxModel(stores);
        return dcm;

    }

    private DefaultComboBoxModel lodCustomersCombo() {
        DefaultComboBoxModel dcm;
        dcm = new DefaultComboBoxModel(customers);
        return dcm;

    }

    private DefaultComboBoxModel lodStoreCustomersCombo() {
        DefaultComboBoxModel dcm;
        dcm = new DefaultComboBoxModel(customers);
        return dcm;
    }

    private DefaultComboBoxModel lodCustStoreCombo() {
        DefaultComboBoxModel dcm;
        dcm = new DefaultComboBoxModel(stores);
        return dcm;

    }

    private DefaultComboBoxModel lodStoreObsrvrCombo() {
        DefaultComboBoxModel dcm;
        dcm = new DefaultComboBoxModel(stores);
        return dcm;

        //  cmbStoresObsrvr.setRenderer(new CategoryListCellRenderer());
    }

    private DefaultComboBoxModel populate() {
        DefaultComboBoxModel dcm;
        dcm = new DefaultComboBoxModel(items);
        return dcm;

    }

    private DefaultComboBoxModel populateCombo() {
        DefaultComboBoxModel dcm;
        dcm = new DefaultComboBoxModel(comboitems);
        return dcm;

    }

    private void addIntiValues() {
        try {
            bMall = new Mall("Mial Mall");
            jTextArea1.append("Mial Mall has been created\n");
            Store gStore;
            Store bStore;
            bFactory = BookStoreFactory.getFactoryInstance();
            bStore = bFactory.createStore();
            bStore.setStoreID("B");
            bStore.setStoreName("Book Store");
            stores.add(bStore);
            jTextArea1.append("A new Store has been added, Store ID: " + bStore.getStoreID() + " ,Store Name: " + bStore.getStoreName() + "\n");

            shFactory = ShoeStoreFactory.getFactoryInstance();
            Store shStore = shFactory.createStore();

            shStore.setStoreID("sh");
            shStore.setStoreName("Shoe Store");
            stores.add(shStore);
            jTextArea1.append("A new Store has been added, Store ID: " + shStore.getStoreID() + " ,Store Name: " + shStore.getStoreName() + "\n");

            gFactory = GameStoreFactory.getFactoryInstance();

            gStore = gFactory.createStore();
            gStore.setStoreID("G");
            gStore.setStoreName("Game Store");
            String str = "A new Store has been added, Store ID: " + gStore.getStoreID() + " ,Store Name: " + gStore.getStoreName();
            jTextArea1.append(str + "\n");
            stores.add(gStore);

            /**
             * **************************************************
             */
            Customer c;
            c = new Customer("c", "Alaa", new ShoppingCart(), jTextArea1);
            Customer d = new Customer("Lujain", "Lujain", new ShoppingCart(), jTextArea1);
            Customer e = new Customer("Mila", "Mila", new ShoppingCart(), jTextArea1);
            Customer f = new Customer("Ahmad", "Ahmad", new ShoppingCart(), jTextArea1);
            Customer g = new Customer("Omar", "Omar", new ShoppingCart(), jTextArea1);
            customers.add(c);
            customers.add(d);
            customers.add(e);
            customers.add(f);
            customers.add(g);
            jTextArea1.append(c.getCustomerName() + " Customer Has been Created " + "\n");
            jTextArea1.append(d.getCustomerName() + " Customer Has been Created " + "\n");
            jTextArea1.append(e.getCustomerName() + " Customer Has been Created " + "\n");
            jTextArea1.append(f.getCustomerName() + " Customer Has been Created " + "\n");
            jTextArea1.append(g.getCustomerName() + " Customer Has been Created " + "\n");
            /**
             * ******************Register
             * observers*******************************
             */
            bStore.registerObserver(g);
            bStore.registerObserver(c);
            gStore.registerObserver(d);
            shStore.registerObserver(e);
            gStore.registerObserver(f);

            /**
             * *************************************************
             */
            ItemComponent ShoeItem
                    = new ComboItem("SHOES", "SPORT COLLECTION");

            ItemComponent babyToyes
                    = new ComboItem("TOYS", "TOYS COLLECTION");
            ItemComponent BookItem;
            BookItem = new ComboItem("BOOKS", "BOOKS COLLECTION");
            comboitems.add(ShoeItem);
            comboitems.add(BookItem);
            comboitems.add(babyToyes);

            BookItem.add(new Item("Purple Teddy Bear", "St", 40.5));
            BookItem.add(new Item("Evan Meets Bucky Lee", "EM", 45.5));
            BookItem.add(new Item("B is for Bicycler", "St", 30.55));
            BookItem.add(new Item("Software Architeture", "C7", 250));
            BookItem.add(new Item("UML for JAVA", "C8", 150));
            BookItem.add(new Item("Software Architeture", "C7", 250));
            
            ShoeItem.add(new Item("Addidas","Addidas", 300));
            ShoeItem.add(new Item("Nike","Nike", 350))   ;      
            ShoeItem.add(new Item("Boots","Boots", 100));
            ShoeItem.add(new Item("Sandals","Sandals", 200));
            
            babyToyes.add(new Item("Lego","Lego", 200));
            babyToyes.add(new Item("Beers","Beers", 140));
            babyToyes.add(new Item("Balls","Balls", 110));
            babyToyes.add(new Item("Car","Car", 50));
             items.add(BookItem);
             items.add(ShoeItem);
             items.add(babyToyes);
             
             BookItem.print();
             ShoeItem.print();
             babyToyes.print();
             
             
            bStore.addItem(BookItem);
            gStore.addItem(babyToyes);
            shStore.addItem(ShoeItem);
        } catch (Exception e) {

        }

    }

    public void clear() {
        txtComboItemName.setText("");
        txtCompoItemID.setText("");
        txtCustomerName.setText("");
        txtItemID.setText("");
        txtItemName.setText("");
        txtItemPrice.setText("");
        txtStoreId.setText("");
        txtStoreName.setText("");
        txtcustomerID.setText("");

    }
}

class ComboBoxRenderer extends DefaultListCellRenderer {

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {

        if (value instanceof ItemComponent) {
            value = ((ItemComponent) value).getName();
        } else if (value instanceof Store) {
            value = ((Store) value).getStoreName();
        } else if (value instanceof Customer) {
            value = ((Customer) value).getCustomerName();
        }

        return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        //To change body of generated methods, choose Tools | Templates.

    }

}
